[build-system]
requires = [
    "argparse~=1.4.0",
    "pandas~=1.3.4",
    "pymongo~=3.12.1",
    "redis~=3.5.3",
    "python-dotenv~=0.19.1",
    "pymongo",
    "tqdm~=4.62.3",
    "numpy~=1.21.4",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"