[build-system]
requires = [
    "argparse",
    "pandas",
    "pymongo",
    "redis",
    "python-dotenv",
    "pymongo",
    "tqdm",
    "numpy",
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"